/**
 * APP CONFIGURATION & LEGAL CONSTANTS
 * Centralized source of truth for app versioning and policy text.
 */

export const APP_VERSION = "1.0.0";
export const APP_NAME = "AI Life Companion";

// Monetization Config
export const FREE_DAILY_LIMIT = 5; // Max reflections per day on free tier

// AI Safety & Policy Disclaimers (Mandatory for Play Store)
export const SAFETY_DISCLAIMER = {
  MEDICAL: "This app is not a medical device. It does not provide clinical advice or therapy. If you are in crisis, please contact professional emergency services.",
  LEGAL: "All generated content is for informational purposes only and does not constitute legal or financial advice.",
  AI_GEN: "Responses are generated by AI. While we strive for accuracy, please verify important information independently.",
};

// UI Constants
export const THEME = {
  COLORS: {
    PRIMARY: "#6366f1", // Indigo
    BACKGROUND: "#0f172a", // Dark Slate
    CARD: "rgba(30, 41, 59, 0.7)", // Glassmorphism base
    TEXT: "#f8fafc",
    ERROR: "#ef4444",
  },
  BORDER_RADIUS: "24px",
};

// API Endpoints (Fallback)
export const ENDPOINTS = {
  LOCAL_LOGS: "idb://reflections",
};

/**
 * Event tracking keys for privacy-first analytics
 */
export const TRACKING_EVENTS = {
  REFLECTION_CREATED: "reflection_created",
  DATA_DELETED: "user_data_wiped",
  PREMIUM_UPGRADE: "premium_status_changed",
  PWA_INSTALLED: "pwa_install_success",
};
